### ISSUE TITLE
to-do before release

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/parat#3]
- [x] check documentation for company_linkage/make sure nothing needs to be updated given current naming/state of things (rebecca)
- [x] write some prose to go on the cset website page that will link to parat (i.e. we will need to make the equivalent page of [this](https://cset.georgetown.edu/research/chinese-state-council-budget-tracker/) - it can be pretty brief, we just need to describe what people can find on the site/its general purpose (rebecca/ngor)
- [x] update descriptive text post-review (rebecca/ngor)
- [x] help id external reviewer(s) (rebecca/ngor/zach)
- [x] Remove this statement from the data_sources text "EDIT IF CNKI IS NOT INCORPORATED BEFORE LAUNCH" (rebecca)
- [x] change permissions on google form so people can provide anonymous feedback? (rebecca)
- [x] figure out/add license to repo (anyone!!)
- [x] 🥕 -> 🦜 everywhere in the code (jennifer)
- [x] add link checker test (jennifer)
- [x] check accessibility again (jennifer)
- [x] add jest tests (jennifer)
- [x] get front-end review (jennifer)
- [x] register domain and push production version of site (jennifer)
- [x] update ALL LINKS to point to production site and to updated repo name (jennifer)
- [x] do final cross-browser compatibility check (jennifer)
- [x] check google analytics setup (jennifer)
